### ISSUE TITLE
Please, share sample your app

### ISSUE THREAD

**Issue by tolu360** [maolion/mao-rn-android-kit#1]
Hello @maolion,

I was wondering if you can share your sample app (as shown in the gif you have on the README) - perhaps as a folder on this repo? This would simplify getting started with your library. Thanks.

**Comment by maolion** [comment]
@tolu360 sample code in the `index.android.js` 

use step
1. clone this repo
2. execute initialize `npm install`
3. run `react-native run-android` you can see this sample demo running in android phone

**Comment by maolion** [comment]
Now, the sample code in the example folder

**Comment by tolu360** [comment]
Thank you @maolion
