### ISSUE TITLE
Not working on react 0.43.

### ISSUE THREAD

**Issue by Juxtlie** [maolion/mao-rn-android-kit#12]
After upgrade react to 0.43. Appbarlayout   stopped working

**Comment by maolion** [comment]
@Juxtlie Would you please tell me more detailed exception information about the AppBarLayout, This can be run on ```react@16.0.0-alpha.6``` and ```react-native@0.43.1```  in the example

**Comment by Juxtlie** [comment]
Sorry. This is was my mistake.
