### ISSUE TITLE
NestedScrollViewAndroid 里面添加listview

### ISSUE THREAD

**Issue by zhangxun86** [maolion/mao-rn-android-kit#2]
你好，我用了你的库，很好用，但我有个新的功能遇到点问题，我在NestedScrollViewAndroid里面添加listview可以正常滚动，但是listview加上下拉刷新功能时，下拉刷新不能运行出来，请问有好的解决吗？

**Comment by maolion** [comment]
@zhangxun86 我正在做，刚好我也需要这个, 在写RecyclerView 并且加上pull to refresh 支持,  这两天会更新上。

**Comment by zhangxun86** [comment]
@maolion 多谢，太好了，好期待！！！

**Comment by maolion** [comment]
@zhangxun86 关于ListView使用下拉刷新的问题，我在example目录里添加了一个 list-view-refresh-control.android.js 样例代码 你可以看下，因为 原生的ListView 有提供RecyclerView的支持，所以只需要把 NestedScrollViewAndroid部分替换成 ListVIew 并且  renderScrollComponent 属性配置为 {props => <RecyclerViewBackedScrollView {...props} />}, 就可以正常使用下拉刷新啦 ，不过这个ListView有另外一个问题，就是在使用 RecyclerViewBackedScrollView 做scrollView的时候好像官方提供的组件并没有处理好，问题是当DataSource里的总数据超出了默认显示的数量时候会导致程序崩溃，不过这个因为是官方组件的问题，我只是说明下。   最后还是建议像这样的需求直接使用原生写好组件套在RN里用会靠谱点。之前计划提供这快的共用组件，后面放弃了，我个人认为还是直接使用原生代码根据业务需求实现好组件模块套在RN里使用 会合理点。

**Comment by zhangxun86** [comment]
@maolion 非常感谢，我有时间试试。

**Comment by maolion** [comment]
> ListView under NestedScrollView inside CoordinatorLayout not scrolling to show all items #5
