### ISSUE TITLE
[Feature Request] CollapsingToolbarLayout

### ISSUE THREAD

**Issue by tolu360** [maolion/mao-rn-android-kit#3]
Hello @maolion,

Thanks for your work on this package. Was wondering if the `CollapsingToolbarLayout` is in your feature roadmap or would you be adding it sometime soon?

Cheers!

**Comment by maolion** [comment]
Yes!

**Comment by tolu360** [comment]
Thanks, looking forward to it!

**Comment by Juxtlie** [comment]
Hello I added collapsing toolbar

**Comment by maolion** [comment]
Now, the CollapsingToolbarLayout component supported in the mao-rn-android-kit
