### ISSUE TITLE
RecyclerViewBackedScrollView being depricated

### ISSUE THREAD

**Issue by teodorszeltins** [maolion/mao-rn-android-kit#6]
Hello!

Firstly, thank you for your work on this packaged. I know many people use it. 

I am currently trying to use this (hiding/showing header on scroll), but since ListView with RecyclerViewBackedScrollView is being deprecated. 
facebook/react-native#11445
facebook/react-native#11095
facebook/react-native#7002

It is also too buggy and no one wants to maintain it on official RN repository.
https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=RecyclerViewBackedScrollView

What is the alternative? I am not a native developer, but it seems that using NestedScrollViewAndroid is not going to perform very well on large infinite scrolling lists and there is no way of getting pull-to-refresh.

**Comment by maolion** [comment]
@teodors 
Please use Android native code to develop a companion native component for use by ReactNative applications
