### ISSUE TITLE
TextInput inside NestedScrollViewAndroid is not focusable

### ISSUE THREAD

**Issue by dgruseck** [maolion/mao-rn-android-kit#7]
Hello,

If I'm going to put a TextInput inside a NestedScrollViewAndroid and click on the TextInput an error is raises from the ScrollResponder:

<img src="https://cloud.githubusercontent.com/assets/3001347/22185980/43b2e6ba-e0ef-11e6-86d4-2443dbe913d1.png" width="300">

Code Example:
```
<NestedScrollViewAndroid
  style={{ height: Dimensions.get('window').height - 70 }}
>
  <TextInput
    style={{ height: 50, backgroundColor: 'yellow' }}
  >
  </TextInput>
</NestedScrollViewAndroid>
```

My dependencies are:

    "mao-rn-android-kit": "^0.3.21",
    "react": "15.4.1",
    "react-native": "0.39.2",

**Comment by maolion** [comment]
Fixed!
