### ISSUE TITLE
错误: NestedScrollViewManager不是抽象的, 并且未覆盖ScrollCommandHandler中的抽象方法

### ISSUE THREAD

**Issue by jiangzhenggeng** [maolion/mao-rn-android-kit#8]
react-native-cli: 2.0.1
react-native: 0.41.2
编译错误，希望能看一下
/node_modules/mao-rn-android-kit/android/src/main/java/com/maornandroidkit/managers/NestedScrollViewManager.java:19: 错误: NestedScrollViewManager不是抽象的, 并且未覆盖ScrollCommandHandler中的抽象方法scrollToEnd(MNestedScrollView,ScrollToEndCommandData)
public class NestedScrollViewManager
       ^
注: /node_modules/mao-rn-android-kit/android/src/main/java/com/maornandroidkit/managers/NestedScrollViewManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误
:mao-rn-android-kit:compileReleaseJavaWithJavac FAILED

**Comment by maolion** [comment]
该问题已修复，请尝试安装最新发布的 npm模块
