### ISSUE TITLE
Native ListView

### ISSUE THREAD

**Issue by luoyushouchai** [maolion/mao-rn-android-kit#9]
您好，问一个问题：我在整合native code与react code的时候出现一个问题，我是想将native端的一个ListView作为一个原生UI组件给react native使用，然而native端的ListView数据的改变不会引起reactnative
ui的重绘，需要我重新scroll以下界面才能重新出来，请问博主有没有什么解决思路？

**Comment by maolion** [comment]
@luoyushouchai ListView是 RecyclerView? 如果是这个问题应该不出在native 那边，应该是在react native  js构建结构这边，你可以试试改变结构看看

**Comment by luoyushouchai** [comment]
@maolion 谢谢
